# Server settings
server:
    port: 8080
    address: localhost

# DATASOURCE
jdbc:
    url: jdbc:log4jdbc:postgresql://localhost:5432/pandapay
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: jerry
    password: jerry

# SPRING settings
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    # Data Source
    # datasource:
        # schema: V1__init.sql

# Flyway settings
flyway:
    locations: db/migration

# MyBatis
mybatis:
    # typeAliasesPackage: org.pandapay.**.domain
    # mapperLocations: classpath:/org/pandapay/**/mapper/*.xml
    config: classpath:/mybatis-config.xml
    executorType: REUSE

# LOGGING
logging:
    level:
       org.mybatis: DEBUG

# spring:
    #    profiles: postgresqldb
# jdbc:
    #    url: jdbc:log4jdbc:postgresql://localhost:5432/pandapay
    #    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    username: jerry
    #    password: jerry
